In [3]:
# write a program to find a user age,day,session  homework,,,,,,,,,;git-summertraning(repo1),repo-summer_training_projects,,,,,,,linked post repo post linked   








# Numpy(np)

In [ ]:
It is basically Numerical python , in this we will be dealing with arrays

In [ ]:
is, in , with 

In [ ]:
is-identity optr(location check )

In [4]:
a=10 
b=10 
a is b 

True

In [5]:
a=[1,2,3]
b=[2,3,1]
a is b

False

In [10]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
c=np.array([1,2,3])
d=np.array([2,4,5])
print(c+d)
print(c-d)
print(c*d)
print(c/d)
print(c//d)
print(c%d)
print(c**d)

[3 6 8]
[-1 -2 -2]
[ 2  8 15]
[0.5 0.5 0.6]
[0 0 0]
[1 2 3]
[  1  16 243]


In [15]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[3,4,6]])


In [17]:
print(a+b)
print(a-b)
print(a*c)
print(a/d)


[[ 3  5  7]
 [ 5  7 10]]
[[-1 -1 -1]
 [-1 -1 -2]]
[[ 1  4  9]
 [ 2  6 12]]
[[0.5  0.5  0.6 ]
 [1.   0.75 0.8 ]]


In [22]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[3,4,6]])



In [27]:
np.transpose(b)



array([[2, 3],
       [3, 4],
       [4, 6]])

In [32]:
np.dot(a,b.T)

array([[20, 29],
       [29, 42]])

In [ ]:
# Q1 write a program to find fibonacci series
# Q2 wap to evaluate a string weather it is pallandrome or not
# Q3 wap to calculate the gross income of a family 
# Q4 wap to make a calculator 





In [ ]:
# fibonacci series
